apiVersion: v1
kind: PersistentVolume
metadata:
 name: citypv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /city
    type: DirectoryOrCreate

---
# persistent volume claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: citypvc
spec:
  volumeName: citypv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi