apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: citypvc
spec:
  volumeName: citypv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi