apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mainpvc
spec:
   volumeName: mainpv
   accessModes:
     - ReadWriteOnce
   storageClassName: standard
   resources:
     requests:
       storage: 1Gi