apiVersion: v1
kind: PersistentVolume
metadata:
  name: mainpv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /main
    type: DirectoryOrCreate

---
# persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mainpvc
spec:
   volumeName: mainpv
   accessModes:
     - ReadWriteOnce
   storageClassName: standard
   resources:
     requests:
       storage: 1Gi