apiVersion: apps/v1
kind: Deployment
metadata:
  name: citylibdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citylibrary
  template:
    metadata:
      labels:
        app: citylibrary
    spec:
      containers:
        - name: citylibrary
          image: milenaj/citylib:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
          - name: DB_HOST
            value: "citydb-service"
          - name: DB_PORT
            value: "27018"
          - name: MAIN_HOST
            value: "mainservice"
          - name: MAIN_PORT
            value: "8080"
