apiVersion: apps/v1
kind: Deployment
metadata:
  name: citydb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citydb
  template:
    metadata:
      labels:
        app: citydb
    spec:
      containers:
        - name: citydb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: citydb
      volumes:
        - name: citydb
          persistentVolumeClaim:
            claimName: citypvc
