apiVersion: apps/v1
kind: Deployment
metadata:
  name: citylibdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citylibrary
  template:
    metadata:
      labels:
        app: citylibrary
    spec:
      containers:
        - name: citylibrary
          image: milenaj/citylib:latest
          ports:
            - containerPort: 8000
          env:
          - name: DB_HOST
            value: "localhost"
          - name: DB_PORT
            value: "27017"
          - name: MAIN_HOST
            value: "mainservice"
          - name: MAIN_PORT
            value: "8080"

        - name: citydb
          image: mongo
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: citydb
      volumes:
        - name: citydb
          persistentVolumeClaim:
            claimName: citypvc