apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainlibdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainlibrary
  template:
    metadata:
      labels:
        app: mainlibrary
    spec:
      containers:
        - name: mainlibrary
          image: milenaj/mainlib:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: MAIN_DB_HOST
            value: "maindb-service"
          - name: MAIN_DB_PORT
            value: "27017"