apiVersion: v1
kind: Service
metadata:
  name: cityservice
spec:
  selector:
    app: citylibrary
  type: ClusterIP  
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001
  type: NodePort