name: Build image and push to docker hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: repository checkout
        uses: actions/checkout@v2
  
      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DH_USERNAME}}
          password: ${{secrets.DH_PASSWORD}}

      - name: main_library image build and push
        run: |
          docker build -t milenaj/mainlib:latest ./lab12/main-library
          docker push milenaj/mainlib:latest
    
      - name: city_library imate build and push
        run: |
          docker build -t milenaj/citylib:latest ./lab12/city-library
          docker push milenaj/citylib:latest
          
  deploy-to-minikube:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0' 

      - name: Configure kubectl to use Minikube
        env:
          KUBECONFIG: /home/runner/.kube/config
        run: |
          mkdir -p ~/.kube ~/.minikube
          scp ~/.kube/config ~/.kube/config
          scp -r ~/.minikube ~/.minikube


      - name: Pull images into Minikube
        run: |
          kubectl get nodes
          docker pull milenaj/mainlib:latest
          docker pull milenaj/citylib:latest
          minikube image load milenaj/mainlib:latest
          minikube image load milenaj/citylib:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./k8s/main-library-deployment.yaml
          kubectl apply -f ./k8s/city-library-deployment.yaml
