name: Build image and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      mainlib_digest: ${{ steps.get_mainlib_digest.outputs.digest }}
      citylib_digest: ${{ steps.get_citylib_digest.outputs.digest }}

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}

      - name: Build and Push main_library
        id: build_mainlib
        run: |
          docker build -t milenaj/mainlib:latest ./lab12/main-library
          docker push milenaj/mainlib:latest

      - name: Get main_library Image Digest
        id: get_mainlib_digest
        run: |
          echo "digest=$(docker inspect --format='{{index .RepoDigests 0}}' milenaj/mainlib:latest)" >> $GITHUB_ENV
        env:
          digest: ${{ env.digest }}

      - name: Build and Push city_library
        id: build_citylib
        run: |
          docker build -t milenaj/citylib:latest ./lab12/city-library
          docker push milenaj/citylib:latest

      - name: Get city_library Image Digest
        id: get_citylib_digest
        run: |
          echo "digest=$(docker inspect --format='{{index .RepoDigests 0}}' milenaj/citylib:latest)" >> $GITHUB_ENV
        env:
          digest: ${{ env.digest }}
      - name: Debug Image Digest
        run: |
          echo "Main Library Digest: ${{ steps.get_mainlib_digest.outputs.digest }}"
          echo "City Library Digest: ${{ steps.get_citylib_digest.outputs.digest }}"


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files
        run: |
          sudo mkdir -p /.minikube/profiles/minikube
          echo "${{ secrets.CA_CERT }}" | sudo tee /.minikube/ca.crt > /dev/null
          echo "${{ secrets.CLIENT_CERT }}" | sudo tee /.minikube/profiles/minikube/client.crt > /dev/null
          echo "${{ secrets.CLIENT_KEY }}" | sudo tee /.minikube/profiles/minikube/client.key > /dev/null
          sudo mkdir -p $HOME/.kube
          sudo cp kubeconfig.yaml $HOME/.kube/config
      - name: Debug Deploy Digests
        run: |
          echo "Main Library Digest for Deployment: ${{ needs.build-and-push.outputs.mainlib_digest }}"
          echo "City Library Digest for Deployment: ${{ needs.build-and-push.outputs.citylib_digest }}"


      - name: Set Up kubectl
        uses: azure/setup-kubectl@v1

      - name: Run kubectl Commands
        run: |
          kubectl get pods --insecure-skip-tls-verify
          kubectl set image deployment/mainlibdepl mainlibrary=milenaj/mainlib@${{ needs.build-and-push.outputs.mainlib_digest }} --insecure-skip-tls-verify
          kubectl set image deployment/citylibdepl citylibrary=milenaj/citylib@${{ needs.build-and-push.outputs.citylib_digest }} --insecure-skip-tls-verify
