apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-ingress
spec:
  rules:
  - host: citylib
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cityservice
            port:
              number: 8000



  